// app/types/database.ts
export type EmailDraft = {
  id?: string;        // Auto-generated by Supabase; optional on insert
  user_id: string;
  title: string;
  template: any;      // JSON design exported from the email editor
  created_at?: string;
  updated_at?: string;
};
